### PR TITLE
Log failed IO that are in a Kamon span

### LINKED ISSUE #4393: Log failed IO that are in a Kamon span
**Motivation**
In order to better understand what goes wrong and see if any improvements can be made on Delta, log the failed IOs that are in Kamon spans.

### PR DESCRIPTION
**Pull request by olivergrabinski**
Closes #4393

### CODE REVIEW

**Comment by olivergrabinski** [comment]
The non-CE `KamonMonitoring` is not concerned by this. Should it be? There will be more logs as the migration goes on.

File: delta/kernel/src/main/scala/ch/epfl/bluebrain/nexus/delta/kernel/kamon/KamonMonitoringCats.scala [hunk 1]
```diff
@@ -62,14 +62,15 @@ object KamonMonitoringCats {
       component: String,
       tags: Map[String, Any] = Map.empty,
       takeSamplingDecision: Boolean = true
-  )(io: IO[A]): IO[A] =
+  )(io: IO[A]): IO[A] = {
     if (enabled)
       buildSpan(name, component, tags).bracketCase(_ => io) {
         case (span, ExitCase.Completed)    => finishSpan(span, takeSamplingDecision)
         case (span, ExitCase.Error(cause)) => failSpan(span, cause, takeSamplingDecision)
```
Comment (imsdu) [inline delta/kernel/src/main/scala/ch/epfl/bluebrain/nexus/delta/kernel/kamon/KamonMonitoringCats.scala:69]: The log may be better here ?

Comment (olivergrabinski) [reply delta/kernel/src/main/scala/ch/epfl/bluebrain/nexus/delta/kernel/kamon/KamonMonitoringCats.scala:69]: I thought it would still make sense to log the errors even if Kamon is disabled 🤔

**Review by imsdu — DISMISSED** [review]

**Review by imsdu — APPROVED** [review]

**Review by imsdu — APPROVED** [review]

**Review by imsdu — DISMISSED** [review]
