### PR TITLE
Fix file indexing in ES + BG in default view

### LINKED ISSUE #3640: Indexing in Blazegraph can cause duplicates
File triples are duplicated in the Blazegraph namespaces.

There is apparently a problem with indexing in Blazegraph.

Example of query returning duplicates (project `bbp/atlas`):
```
SELECT ?id ?p ?o
WHERE {
  ?id a nxv:File ;
      nxv:digest / nxv:value 'DIGEST'.
  ?id ?p ?o;
}
ORDER BY ?p
```

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #3640

### CODE REVIEW

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala [hunk 1]
```diff
@@ -76,4 +76,11 @@ class SelectPredicatesSuite extends BioSuite {
     pipe(Set(rdfs.label)).apply(element).assert(expected)
     defaultPipe.apply(element).assert(expected)
   }
+
+  test("Do not apply any modifications for a forward type 'File'") {
+    val types = Set(nxv + "PullRequest", nxv + "File")
+    val file  = element.copy(value = element.value.copy(types = types))
+    pipe(Set(rdfs.label)).apply(element).assert(file)
+    defaultPipe.apply(file).assert(file)
```
Comment (shinyhappydan) [inline delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala:84]: Why is element passed to the first, but file to the second?

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala [hunk 2]
```diff
@@ -54,7 +54,7 @@ class SelectPredicatesSuite extends BioSuite {
     registry
       .lookupA[SelectPredicates.type](SelectPredicates.ref)
       .rightValue
-      .withJsonLdConfig(SelectPredicatesConfig(predicates).toJsonLd)
+      .withJsonLdConfig(SelectPredicatesConfig(None, predicates).toJsonLd)
```
Comment (shinyhappydan) [inline delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala:57]: Should the forward type `File` be set here?

File: delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicates.scala [hunk 3]
```diff
@@ -27,17 +27,21 @@ class SelectPredicates(config: SelectPredicatesConfig) extends Pipe {
   override def inType: Typeable[GraphResource]  = Typeable[GraphResource]
   override def outType: Typeable[GraphResource] = Typeable[GraphResource]
 
-  override def apply(element: SuccessElem[GraphResource]): Task[Elem[GraphResource]] = {
-    val id       = subject(element.value.id)
-    val newGraph = element.value.graph.filter { case (s, p, _) => s == id && config.nodeSet.contains(p) }
-    val newState = element.value.copy(graph = newGraph, types = newGraph.rootTypes)
-    Task.pure(element.copy(value = newState))
+  override def apply(element: SuccessElem[GraphResource]): Task[Elem[GraphResource]] = Task.pure {
+    if (config.forwardTypes.exists { p => p.exists(element.value.types.contains) }) {
```
Comment (shinyhappydan) [inline delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicates.scala:31]: Maybe a name for this predicate like `isAForwardType` is useful here?

File: tests/src/test/scala/ch/epfl/bluebrain/nexus/tests/kg/StorageSpec.scala [hunk 4]
```diff
@@ -330,6 +329,79 @@ abstract class StorageSpec extends BaseSpec with CirceEq {
...
+        Coyote,
+        "project"     -> fullId,
+        "storageId"   -> storageId,
+        "storageType" -> storageType
+      )
+      val expected = jsonContentOf("/kg/files/list.json", mapping: _*)
+      filterSearchMetadata
+        .andThen(filterResults(Set("_location")))(json) should equalIgnoreArrayOrder(expected)
+    }
+  }
```
Comment (shinyhappydan) [inline tests/src/test/scala/ch/epfl/bluebrain/nexus/tests/kg/StorageSpec.scala:345]: Is this just a test that was missing previously?

File: delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicates.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (olivergrabinski) [reply delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicates.scala:31]: Invariant type?

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala (hunk 1 above)
Comment (olivergrabinski) [inline delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala:84]: Shouldn't both assertions do either `.apply(file)` or `.apply(element)`?

File: delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicates.scala (hunk 3 above)
Comment (imsdu) [reply delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicates.scala:31]: Invariant type sounds nice

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala (hunk 2 above)
Comment (imsdu) [reply delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala:57]: It could, I chose not to

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala (hunk 1 above)
Comment (imsdu) [reply delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala:84]: It is still an elem which contains a file. I will make that more explicit

File: tests/src/test/scala/ch/epfl/bluebrain/nexus/tests/kg/StorageSpec.scala (hunk 4 above)
Comment (imsdu) [reply tests/src/test/scala/ch/epfl/bluebrain/nexus/tests/kg/StorageSpec.scala:345]: Yes

File: delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicates.scala (hunk 3 above)
Comment (imsdu) [reply delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicates.scala:31]: I will let as it is for now

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala [hunk 5]
```diff
@@ -69,11 +75,25 @@ class SelectPredicatesSuite extends BioSuite {
     pipe(Set.empty).apply(element).assert(expected)
   }
 
-  test("Retain matching predicates") {
-    val graph    = Graph.empty(base / "id").add(rdfs.label, "active").add(Vocabulary.rdf.tpe, nxv + "PullRequest")
-    val types    = Set(nxv + "PullRequest")
-    val expected = element.copy(value = element.value.copy(graph = graph, types = types))
-    pipe(Set(rdfs.label)).apply(element).assert(expected)
```
Comment (imsdu) [inline delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala:76]: There was a problem there, this was never executed

**Review by olivergrabinski — APPROVED** [review]

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala (hunk 2 above)
Comment (shinyhappydan) [reply delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/pipes/SelectPredicatesSuite.scala:63]: Did this not indicate a problem?

**Review by shinyhappydan — APPROVED** [review]
