### PR TITLE
Fixing assigning the correct error when Elasticsearch indexing fails

### LINKED ISSUE #3720: Errors from bulk ES responses can be associated with wrong resource

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #3720

### CODE REVIEW

File: delta/plugins/elasticsearch/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/indexing/ElasticSearchSinkSuite.scala [hunk 1]
```diff
@@ -68,20 +69,42 @@ class ElasticSearchSinkSuite extends BioSuite with ElasticSearchClientSetup.Fixt
...
+      _       = assert(
+                  result.lift(1).flatMap(_.toThrowable).exists(_.isInstanceOf[BulkUpdateException]),
+                  "We expect a 'BulkUpdateException' as an error here"
+                )
+      // The valid one should remain a success and hold a Unit value
+      _       = assert(result.lift(2).flatMap(_.toOption).contains(()))
+      _      <- client
+                  .search(QueryBuilder.empty, Set(index.value), Query.Empty)
+                  .map(_.sources.toSet)
+                  .assert(Set(bob, judy, alice).flatMap(_._2.asObject))
```
Comment (shinyhappydan) [inline delta/plugins/elasticsearch/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/indexing/ElasticSearchSinkSuite.scala:107]: These test cases make sense, but MUnit is meaning this test doesn't read very clearly

**Review by olivergrabinski — APPROVED** [review]
