### PR TITLE
Use the write db pool when fetching project context for write operations

### LINKED ISSUE #5016: Fetching the project context during write operations should be done on the write pool
**Describe the bug**
When we create a project, we automatically create some resources (storage/resolver/view)
However when Nexus is using a PostgreSQL cluster, there may be some replication delays and fetching the context of the new project can fail and the creation of those default resources can't be completed.

**Expected behavior**
When fetching the context for a write operation, this should be done from the primary node

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #5016

### CODE REVIEW

File: delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/projects/FetchContext.scala [hunk 1]
```diff
@@ -53,42 +53,51 @@ abstract class FetchContext { self =>
...
+      fetchProject: (ProjectRef, Boolean) => IO[Option[ProjectResource]],
       quotas: Quotas
   ): FetchContext =
     new FetchContext {
 
       override def defaultApiMappings: ApiMappings = dam
 
       override def onRead(ref: ProjectRef): IO[ProjectContext] =
-        fetchProject(ref).flatMap {
+        fetchProject(ref, false).flatMap {
```
Comment (dantb) [inline delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/projects/FetchContext.scala:93]: Named parameter may be a bit clearer for the flag. Same below

**Review by dantb — APPROVED** [review]

File: delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/projects/FetchContext.scala (hunk 1 above)
Comment (imsdu) [reply delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/projects/FetchContext.scala:93]: We can't use them here with a function passed as a parameter
