### PR TITLE
Retry on the destroy method in supervisor in case of failure

### LINKED ISSUE #3894: Investigate why some projections are not properly cleaned up
When we deploy a new version of a composite views, the former version of its progress, its namespace and its index are not properly destroyed.

We should make sure that:
* An error log is displayed whenever this situation happens
* We should retry when this fails (whenever we update the search config, a lot of pressure is put in Blazegraph which is the main suspect here on why the deletion is not properly executed)

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #3894

### CODE REVIEW

File: delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/ExecutionStrategy.scala [hunk 1]
```diff
@@ -21,7 +21,7 @@ sealed trait ExecutionStrategy extends Product with Serializable {
     *   the cluster configuration
     */
   def shouldRun(name: String, cluster: ClusterConfig): Boolean = this match {
-    case _: SingleNode => name.hashCode % cluster.size == cluster.nodeIndex
+    case _: SingleNode => Math.abs(name.hashCode) % cluster.size == cluster.nodeIndex
```
Comment (imsdu) [inline delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/ExecutionStrategy.scala:24]: Hashcode can be negative

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/SupervisionSuite.scala [hunk 2]
```diff
@@ -353,4 +348,60 @@ class SupervisionSuite extends BioSuite with SupervisorSetup.Fixture with Doobie
...
+  }
+
+  test("Run and properly destroy a projection with an failing destroy method") {
+    val projection = ProjectionMetadata("test", "unstable-global-projection", None, None)
+    for {
+      // Starting the projection
+      started <- Ref.of[Task, Boolean](false)
+      compiled = CompiledProjection.fromStream(projection, ExecutionStrategy.EveryNode, evalStream(started.set(true)))
+      _       <- sv.run(compiled).eventually(ExecutionStatus.Running)
+      _       <- started.get.eventually(true)
```
Comment (shinyhappydan) [inline delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/SupervisionSuite.scala:375]: Would be nice to hide this boilerplate

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/SupervisionSuite.scala [hunk 3]
```diff
@@ -353,4 +348,60 @@ class SupervisionSuite extends BioSuite with SupervisorSetup.Fixture with Doobie
...
+      // Destroy the projection with a destroy method that will always fail
+      failing  = Task.raiseError(new IllegalStateException("Fail !"))
```
Comment (shinyhappydan) [inline delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/SupervisionSuite.scala:377]: if you name this variable "alwaysFails" then there is no need for this comment

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/SupervisionSuite.scala [hunk 4]
```diff
@@ -353,4 +348,60 @@ class SupervisionSuite extends BioSuite with SupervisorSetup.Fixture with Doobie
...
+      _       <- sv.destroy(projection.name, failing)
+      // The projection should have stopped
+      _       <- sv.describe(projection.name).eventuallyNone
```
Comment (shinyhappydan) [inline delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/SupervisionSuite.scala:380]: If you make a method assertStopped(projection) then it's more readable and you don't need this comment

File: delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/Supervisor.scala [hunk 5]
```diff
@@ -356,7 +360,13 @@ object Supervisor {
                               _      <- Task.delay(log.info(s"Destroying '${metadata.module}/${metadata.name}'..."))
                               _      <- stopProjection(s)
                               _      <- Task.when(s.executionStrategy == PersistentSingleNode)(projections.delete(name))
-                              _      <- clear
+                              _      <- onDestroy
+                                          .retryingOnSomeErrors(
+                                            retryStrategy.retryWhen,
+                                            retryStrategy.policy,
+                                            retryStrategy.onError
+                                          )
```
Comment (shinyhappydan) [inline delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/Supervisor.scala:368]: Can we make it so that this method just takes a retry strategy? Would be much more readable

**Review by shinyhappydan — DISMISSED** [review]

File: delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/Supervisor.scala (hunk 5 above)
Comment (imsdu) [reply delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/Supervisor.scala:368]: I created an issue to introduce this method and replace it everywhere #3928

File: delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/SupervisorSuite.scala [hunk 6]
```diff
@@ -0,0 +1,307 @@
...
+  }
+
+  test("Run and properly destroy a projection with an failing destroy method") {
+    val projection = ProjectionMetadata("test", "unstable-global-projection", None, None)
+    for {
+      _         <- assertStart(projection, EveryNode)
+      alwaysFail = Task.raiseError(new IllegalStateException("Fail !"))
+      _         <- assertDestroy(projection, alwaysFail)
+    } yield ()
+  }
```
Comment (shinyhappydan) [inline delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/SupervisorSuite.scala:282]: This is pretty nice, but a small change like this can help make it more like given/when/then

```
  test("Run and properly destroy a projection with an unstable destroy method") {
    val projection = ProjectionMetadata("test", "unstable-global-projection", None, None)
    val destroyThatAlwaysFails = Task.raiseError(new IllegalStateException("Fail !"))

    for {
      _               <- startProjection(projection, EveryNode)
      _               <- destroyProjection(projection, destroyThatFailsThenSucceeds)
      _               <- assertProjectionIsDestroyed(projection)
    } yield ()
  }
```

I realise that technically we are asserting during the startup, but it's not necessary to communicate this, only that the start is what is happening

**Review by shinyhappydan — DISMISSED** [review]

**Review by olivergrabinski — APPROVED** [review]
