### PR TITLE
Fix resolver related issues

### LINKED ISSUE #2342: Error on ResolverRejection.DifferentResolverType flipped expected with found

### LINKED ISSUE #2343: The error message when creating a resolver with a bad priority is missing the word priority

### LINKED ISSUE #2349: The error message when a resource can't be resolved though the resolver endpoint should be updated

### LINKED ISSUE #2350: fetching a resource through resolver resolution using tag and rev query params is not supported

### LINKED ISSUE #2351: The resolver report should include the successful project

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #2342
Fixes #2343
Fixes #2349
Fixes #2350
Fixes #2351

NB: I opted for a `Option[Either[Long, TagLabel]]` to pass the version because if we introduce a 4th way to fetch with timestamp, we will refactor how we fetch stuff (and therefore this endpoint) anyway.

### CODE REVIEW

File: delta/app/src/test/scala/ch/epfl/bluebrain/nexus/delta/routes/ResolversRoutesSpec.scala [hunk 1]
```diff
@@ -115,8 +115,8 @@ class ResolversRoutesSpec
   def fetchSchema: (ResourceRef, ProjectRef) => IO[ResourceNotFound, SchemaResource] =
     (ref: ResourceRef, p: ProjectRef) =>
       ref match {
-        case Latest(i) if i == schemaId => IO.pure(resourceFS)
-        case _                          => IO.raiseError(ResourceNotFound(ref.iri, p))
+        case Revision(_, i, 5L) if i == schemaId => IO.pure(resourceFS)
```
Comment (umbreak) [inline delta/app/src/test/scala/ch/epfl/bluebrain/nexus/delta/routes/ResolversRoutesSpec.scala:118]: what is this 5L ?

**Review by umbreak — CHANGES_REQUESTED** [review]

File: delta/sdk/src/test/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/resolvers/MultiResolutionSpec.scala [hunk 2]
```diff
@@ -58,9 +59,9 @@ class MultiResolutionSpec
   def fetch: (ResourceRef, ProjectRef) => Fetch[ReferenceExchangeValue[_]] =
     (ref: ResourceRef, _: ProjectRef) =>
       ref match {
-        case Latest(i) if i == resourceId => IO.some(resourceValue)
-        case Latest(i) if i == schemaId   => IO.some(schemaValue)
-        case _                            => IO.none
+        case Latest(i) if i == resourceId       => IO.some(resourceValue)
```
Comment (umbreak) [inline delta/sdk/src/test/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/resolvers/MultiResolutionSpec.scala:62]:
```scala
case Latest(`resourceId`) => IO.some(resourceValue)
case Revision(_, `schemaId`, _) => IO.some(schemaValue)
case _ => IO.none
```

**Review by umbreak — CHANGES_REQUESTED** [review]

**Review by umbreak — APPROVED** [review]
