### PR TITLE
Fix issues found in itegration tests

### LINKED ISSUE #1804: Fix issues found by integration tests.
- [x] 1. when trying to create an org that already exists, `label` field is missing in the error response
- [x] 2. missing `orgLabel` and `label` fields in error response when trying to create a project that already exists.
- [x] 3. missing `provided` and `expected` fields in error response when incorrect revision is used
- [x] 4. ~missing _label in response when creating/updating realm~ (will be handled in #1809)
- [x] 5. checking for orgs/projects write permissions instead of create
- [x] 6. ~`_authorizationEndpoint`, `_endSessionEndpoint`, `_grantTypes`, `_issuer`, `_tokenEndpoint`, `_userInfoEndpoint` fields are returned for deprecated realms~
- [ ] 7. can't list projects for an organization

### PR DESCRIPTION
**Pull request by wwajerowicz**
Fixes #1804

### CODE REVIEW

File: delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/routes/ProjectsRoutes.scala [hunk 1]
```diff
@@ -8,7 +8,7 @@ import akka.http.scaladsl.server._
 import cats.implicits._
 import ch.epfl.bluebrain.nexus.delta.rdf.jsonld.context.{ContextValue, RemoteContextResolution}
 import ch.epfl.bluebrain.nexus.delta.rdf.utils.JsonKeyOrdering
-import ch.epfl.bluebrain.nexus.delta.routes.directives.DeltaDirectives._
+import ch.epfl.bluebrain.nexus.delta.routes.directives.DeltaDirectives.{label, _}
```
Comment (umbreak) [inline delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/routes/ProjectsRoutes.scala:11]: import ch.epfl.bluebrain.nexus.delta.routes.directives.DeltaDirectives._

File: delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/routes/ProjectsRoutes.scala [hunk 2]
```diff
@@ -166,6 +169,11 @@ final class ProjectsRoutes(identities: Identities, acls: Acls, projects: Project
                   }
                 }
               }
+            },
+            (get & label & pathEndOrSingleSlash & extractUri & paginated & projectsSearchParams) {
```
Comment (umbreak) [inline delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/routes/ProjectsRoutes.scala:173]: Can you just add a comment on the lines of:
```scala
// List all projects belonging to an organization ''label''
```

**Review by umbreak — CHANGES_REQUESTED** [review]

File: delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/projects/ProjectRejection.scala [hunk 3]
```diff
@@ -101,10 +101,15 @@ object ProjectRejection {
 
   implicit private[model] val projectRejectionEncoder: Encoder.AsObject[ProjectRejection] =
     Encoder.AsObject.instance { r =>
-      val tpe = ClassUtils.simpleName(r)
+      val tpe     = ClassUtils.simpleName(r)
+      val default = JsonObject.empty.add(keywords.tpe, tpe.asJson).add("reason", r.reason.asJson)
       r match {
         case WrappedOrganizationRejection(rejection) => rejection.asJsonObject
-        case _                                       => JsonObject.empty.add(keywords.tpe, tpe.asJson).add("reason", r.reason.asJson)
+        case IncorrectRev(provided, expected)        =>
```
Comment (umbreak) [inline delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/projects/ProjectRejection.scala:108]: I guess `IncorrectRev` and `RevisionNotFound` should be addressed in all rejections, not only in `ProjectRejection `

**Review by umbreak — CHANGES_REQUESTED** [review]

**Review by umbreak — APPROVED** [review]

**Review by imsdu — APPROVED** [review]
