### PR TITLE
Fix migration issues + improve errors and logs

### LINKED ISSUE #1996: Migrating resources with nested base
Nesting bases are not allowed anymore so importing resources such as:
```json
{
  "@context" : [
    "https://bbp.neuroshapes.org",
    "https://bluebrain.github.io/nexus/contexts/resource.json"
  ],
  "@id" : "01e04bad-d48b-4f63-8b69-2721f6391028",
  "@type" : [
    "Entity",
    "SliceCollection"
  ],
  "identifier" : "99",
  "name" : "99",
  "wasDerivedFrom" : {
    "@id" : "https://bbp.epfl.ch/neurosciencegraph/data/0d38b53f-aa1d-4e30-9224-267dd4c581d0",
    "@type" : [
      "Entity",
      "Subject"
    ]
  },
  "_self" : "https://bbp.epfl.ch/nexus/v1/resources/bbp/neocortex/datashapes:slicecollection/01e04bad-d48b-4f63-8b69-2721f6391028",
  "_constrainedBy" : "nsg:dash/slicecollection",
  "_project" : "https://bbp.epfl.ch/nexus/v1/projects/bbp/neocortex",
  "_rev" : 1,
  "_deprecated" : false,
  "_createdAt" : "2019-04-08T08:44:15.022Z",
  "_createdBy" : "https://bbp.epfl.ch/nexus/v1/realms/bbp/users/akkaufma",
  "_updatedAt" : "2019-04-08T08:44:15.022Z",
  "_updatedBy" : "https://bbp.epfl.ch/nexus/v1/realms/bbp/users/akkaufma"
}
```
fails as the id is not properly expanded.
To fix this, we must get the base and append it to the context of the resource.

The error:
```json
{"@type":"UnexpectedResourceId","reason":"Resource 'https://bbp.epfl.ch/neurosciencegraph/data/01e04bad-d48b-4f63-8b69-2721f6391028' does not match resource id on payload '01e04bad-d48b-4f63-8b69-2721f6391028'."}```

The context:
```
{"@context":["https://neuroshapes.org",{"@vocab":"https://bbp.epfl.ch/nexus/v1/resources/bbp/neocortex/_/","@base":"https://bbp.epfl.ch/neurosciencegraph/data/"}]}
```

### LINKED ISSUE #1998: Migrated resource can't be properly validated with the given schema
When creating resource:
```json
{
  "@context" : "https://bbp.neuroshapes.org",
  "@id" : "https://bbp.epfl.ch/neurosciencegraph/data/fc17c5d9-69cf-4822-b58f-7a6abdd5c4e2",
  "@type" : [
    "prov:Entity",
    "nsg:Subject"
  ],
  "age" : {
    "period" : "Post-natal",
    "unitCode" : "years",
    "value" : {
      "@value" : 26,
      "@type" : "xsd:integer"
    }
  },
  "disease" : {
    "@id" : "https://meshb.nlm.nih.gov/record/ui?ui=D001932",
    "label" : "Brain Neoplasms"
  },
  "name" : "H16.06.007",
  "sex" : {
    "@id" : "http://purl.obolibrary.org/obo/PATO_0000384",
    "label" : "male"
  },
  "species" : {
    "@id" : "https://www.ncbi.nlm.nih.gov/taxonomy/9606",
    "label" : "Homo sapiens"
  },
  "identifier" : "518229880"
}
```
We get the error:
```json
{"@type":"InvalidResource","reason":"Resource 'https://bbp.epfl.ch/neurosciencegraph/data/fc17c5d9-69cf-4822-b58f-7a6abdd5c4e2' failed to validate against the constraints defined in schema 'https://neuroshapes.org/dash/subject'","details":{"@context":"https://bluebrain.github.io/nexus/contexts/shacl-20170720.json","@type":"sh:ValidationReport","conforms":false,"result":{"@type":"sh:ValidationResult","detail":[{"@type":"sh:ValidationResult","focusNode":"https://bbp.epfl.ch/neurosciencegraph/data/fc17c5d9-69cf-4822-b58f-7a6abdd5c4e2","resultMessage":"Value does not have all the shapes in the sh:and enumeration","resultSeverity":"sh:Violation","sourceConstraintComponent":"sh:AndConstraintComponent","sourceShape":"https://neuroshapes.org/commons/subject/shapes/SubjectShape","value":"https://bbp.epfl.ch/neurosciencegraph/data/fc17c5d9-69cf-4822-b58f-7a6abdd5c4e2"}],"focusNode":"https://bbp.epfl.ch/neurosciencegraph/data/fc17c5d9-69cf-4822-b58f-7a6abdd5c4e2","resultMessage":"Value does not have shape <https://neuroshapes.org/commons/subject/shapes/SubjectShape>","resultSeverity":"sh:Violation","sourceConstraintComponent":"sh:NodeConstraintComponent","sourceShape":"https://neuroshapes.org/dash/subject/shapes/SubjectShape","value":"https://bbp.epfl.ch/neurosciencegraph/data/fc17c5d9-69cf-4822-b58f-7a6abdd5c4e2"},"targetedNodes":1}}
```
The context:
```
{"@context":["https://neuroshapes.org",{"@vocab":"https://bbp.epfl.ch/nexus/v1/resources/bbp/neocortex/_/","@base":"https://bbp.epfl.ch/neurosciencegraph/data/"}]}
```
The schema https://neuroshapes.org/Subject:
```
{"@id":"https://neuroshapes.org/dash/subject","prov:wasDerivedFrom":"https://github.com/INCF/neuroshapes/blob/v0.3.15/modules/core/src/main/resources/schemas/neurosciencegraph/core/subject/v0.1.0.json","shapes":[{"node":"https://neuroshapes.org/commons/subject/shapes/SubjectShape","@id":"this:SubjectShape","@type":"sh:NodeShape","label":"Subject shape definition","comment":"Subject used in experiment","targetClass":"nsg:Subject"}],"@context":["https://incf.github.io/neuroshapes/contexts/schema.json",{"this":"https://neuroshapes.org/dash/subject/shapes/"},"https://bluebrain.github.io/nexus/contexts/shacl-20170720.json"],"@type":"nxv:Schema","imports":["https://neuroshapes.org/commons/subject"]}
```

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #1996 
Fixes #1998

### CODE REVIEW

File: delta/migration/src/test/scala/ch/epfl/bluebrain/nexus/migration/v1_4/SourceSanitizerSpec.scala [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import org.scalatest.matchers.should.Matchers
+import org.scalatest.wordspec.AnyWordSpecLike
+
+class SourceSanitizerSpec extends AnyWordSpecLike with Matchers with CirceLiteral {
+
+  "Replacing old contexts" should {
+
+    "work in an array" in {
+      val original =
+        json"""{"@context" : ["https://bbp.neuroshapes.org","https://bluebrain.github.io/nexus/contexts/resource.json"]}"""
```
Comment (bogdanromanx) [inline delta/migration/src/test/scala/ch/epfl/bluebrain/nexus/migration/v1_4/SourceSanitizerSpec.scala:13]: this is very specific to BBP, is there a way to handle this problem without fixed contexts?

**Review by bogdanromanx — APPROVED** [review]

File: delta/migration/src/test/scala/ch/epfl/bluebrain/nexus/migration/v1_4/SourceSanitizerSpec.scala (hunk 1 above)
Comment (imsdu) [reply delta/migration/src/test/scala/ch/epfl/bluebrain/nexus/migration/v1_4/SourceSanitizerSpec.scala:13]: We can handle it via some configuration but I want to test things and have a better idea first

**Review by bogdanromanx — APPROVED** [review]
