### PR TITLE
deal with missing files in DiskStorageFetchFile 

### LINKED ISSUE #3817: Report a clean error message when a File is missing from Storage
## Description
Current Delta returns a broken stream, we should have a proper HTTP status code returned and a meaningful error message.

### PR DESCRIPTION
**Pull request by shinyhappydan**
Fixed #3817 

previously returned a stream which would break

### CODE REVIEW

File: delta/plugins/storage/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/storages/operations/disk/DiskStorageFetchFileSpec.scala [hunk 1]
```diff
@@ -30,6 +31,14 @@ class DiskStorageFetchFileSpec
...
 
+    "deal with a missing file" in {
+      val volume       = Files.createTempDirectory("disk-access")
+      val file         = volume.resolve("my/file.txt")
+      Files.createDirectories(file.getParent)
+      val fullFilePath = file.toString
+
+      DiskStorageFetchFile(Uri.Path(fullFilePath)).rejected shouldEqual FetchFileRejection.FileNotFound(fullFilePath)
+    }
+  }
```
Comment (shinyhappydan) [inline delta/plugins/storage/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/storages/operations/disk/DiskStorageFetchFileSpec.scala:43]: I would have converted this test to MUnit, however it's using an Akka trait and it didn't seem worth it for this story

File: delta/plugins/storage/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/storages/operations/disk/DiskStorageFetchFile.scala [hunk 2]
```diff
@@ -20,7 +20,9 @@ object DiskStorageFetchFile extends FetchFile {
 
   override def apply(path: Uri.Path): IO[FetchFileRejection, AkkaSource] =
     Try(Paths.get(URI.create(s"file://$path"))) match {
-      case Failure(err)   => IO.raiseError(UnexpectedLocationFormat(s"file://$path", err.getMessage))
-      case Success(value) => UIO.pure(FileIO.fromPath(value))
+      case Failure(err)  => IO.raiseError(UnexpectedLocationFormat(s"file://$path", err.getMessage))
+      case Success(path) =>
+        IO.raiseWhen(!path.toFile.exists())(FetchFileRejection.FileNotFound(path.toString))
```
Comment (shinyhappydan) [inline delta/plugins/storage/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/storages/operations/disk/DiskStorageFetchFile.scala:25]: Would want to double check this is how we interact with the file system, I wonder if there is a different library we might use. FileIO didn't seem to have this but perhaps I missed it
