### PR TITLE
Fix tag routes

### LINKED ISSUE #1903: Tagging a resource fails
Tagging a resource fails with the message:
```
{
  "@context" : "https://bluebrain.github.io/nexus/contexts/error.json",
  "@type" : "MalformedQueryParamRejection",
  "reason" : "The query parameter 'rev' was malformed.",
  "details" : "the provided query parameter should not be present"
}
```
As the rev query parameter must be present, maybe a route collision ?

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #1903 

Fixes:
* Tag route
* Tag regexp
* Tag creation http code

### CODE REVIEW

File: delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/TagLabel.scala [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+import ch.epfl.bluebrain.nexus.delta.sdk.error.FormatError
+import ch.epfl.bluebrain.nexus.delta.sdk.error.FormatError.IllegalTagFormatError
+import io.circe.{Decoder, Encoder}
+
+/**
+  * A safe representation of a tag label
+  *
+  * @param value the string representation of the tag label
+  */
+final case class TagLabel private (value: String) {
```
Comment (umbreak) [inline delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/TagLabel.scala:13]: cannot be `extends Anyval` ?

File: delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/TagLabel.scala [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+  override def toString: String = value
+}
+
+object TagLabel {
+
+  private[sdk] val maxLength = 32
```
Comment (umbreak) [inline delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/TagLabel.scala:19]: Is that the only restriction? I would not like to allow tags with no-ascii characters...that could lead to undesired behaviour. I think I slight modification from Label should actually be enough:
```scala
  private[sdk] val regex = "[a-zA-Z0-9_-[.]]{1,32}".r
```

**Review by umbreak — CHANGES_REQUESTED** [review]

**Review by wwajerowicz — APPROVED** [review]

**Review by umbreak — APPROVED** [review]
