### PR TITLE
Fix conflicts between view routes.

### LINKED ISSUE #2093: Once blazegraph and elasticsearch module are merged, use rejectOn for colliding routes

### PR DESCRIPTION
**Pull request by wwajerowicz**
Fixes #2093

### CODE REVIEW

File: delta/plugins/blazegraph/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/blazegraph/routes/BlazegraphViewsRoutes.scala [hunk 1]
```diff
@@ -95,17 +95,17 @@ class BlazegraphViewsRoutes(
...
-                                emit(views.update(id, ref, rev, source).map(_.void))
+                                emit(views.update(id, ref, rev, source).map(_.void).rejectOn[DecodingFailed])
                             }
                           }
                         },
                         (delete & parameter("rev".as[Long])) { rev =>
                           // Deprecate a view
                           authorizeFor(AclAddress.Project(ref), permissions.write).apply {
-                            emit(views.deprecate(id, ref, rev).map(_.void))
+                            emit(views.deprecate(id, ref, rev).map(_.void).rejectOn[ViewNotFound])
```
Comment (umbreak) [inline delta/plugins/blazegraph/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/blazegraph/routes/BlazegraphViewsRoutes.scala:108]: what about `ViewNotFound`?

File: delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchViewsRoutes.scala [hunk 2]
```diff
@@ -104,17 +104,17 @@ final class ElasticSearchViewsRoutes(
                               (parameter("rev".as[Long].?) & pathEndOrSingleSlash & entity(as[Json])) {
                                 case (None, source)      =>
                                   // Create an elasticsearch view with id segment
-                                  emit(Created, views.create(id, ref, source).map(_.void))
+                                  emit(Created, views.create(id, ref, source).map(_.void).rejectOn[DecodingFailed])
                                 case (Some(rev), source) =>
                                   // Update a view
-                                  emit(views.update(id, ref, rev, source).map(_.void))
+                                  emit(views.update(id, ref, rev, source).map(_.void).rejectOn[DecodingFailed])
```
Comment (umbreak) [inline delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchViewsRoutes.scala:110]: what about `ViewNotFound`?

**Review by umbreak — CHANGES_REQUESTED** [review]

File: delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchViewsRoutes.scala (hunk 2 above)
Comment (wwajerowicz) [reply delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchViewsRoutes.scala:110]: `DecodingFailed` happens before `ViewNotFound`

Comment (umbreak) [reply delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchViewsRoutes.scala:110]: Yes, but It doesn't hurt to add that too, right? Since we could change the order of rejections and many things will keep working

**Review by umbreak — DISMISSED** [review]

File: delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/syntax/IOSyntax.scala [hunk 3]
```diff
@@ -32,6 +32,13 @@ final class IOFunctorOps[E, A, F[_]: Functor](private val io: IO[E, F[A]]) {
 
 final class RejectionOrErrorOps[E: JsonLdEncoder: HttpResponseFields: Encoder, A](private val io: IO[E, A]) {
 
+  /**
+    * Helper method to convert the error channel of the IO to a [[CustomAkkaRejection]] whenever the passed ''filter'' is true.
+    * If the [[PartialFunction]] does not apply, the error channel is left untouched.
+    */
+  def rejectWhen(filter: PartialFunction[E, Boolean]): IO[Response[E], A] =
```
Comment (umbreak) [inline delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/syntax/IOSyntax.scala:39]: why do you need this?

File: delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchViewsRoutes.scala [hunk 4]
```diff
@@ -88,7 +88,7 @@ final class ElasticSearchViewsRoutes(
                     // Create an elasticsearch view without id segment
                     (post & pathEndOrSingleSlash & noParameter("rev") & entity(as[Json])) { source =>
                       authorizeFor(AclAddress.Project(ref), permissions.write).apply {
-                        emit(Created, views.create(ref, source).map(_.void).rejectOn[DecodingFailed])
+                        emit(Created, views.create(ref, source).map(_.void).rejectWhen(decodingFailedOrViewNotFound))
```
Comment (umbreak) [inline delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchViewsRoutes.scala:91]: just do:
```scala
views.create(ref, source).map(_.void).rejectOn {
   case _: DecodingFailed | _: ViewNotFound => true
}
```

**Review by umbreak — CHANGES_REQUESTED** [review]

**Review by umbreak — APPROVED** [review]

File: delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/syntax/IOSyntax.scala (hunk 3 above)
Comment (wwajerowicz) [reply delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/syntax/IOSyntax.scala:39]: it's used in the routes

Comment (umbreak) [reply delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/syntax/IOSyntax.scala:39]: I got confused because you changed `rejectOn` previously. Now I see the difference

**Review by umbreak — APPROVED** [review]

**Review by umbreak — APPROVED** [review]
