### PR TITLE
Fix composite views clean up

### LINKED ISSUE #3913: On a database outage, composite views start reindexing from the start
**Describe the bug**
When there is a database outage, the coordinator responsible for composite views gets restarted and start reindexing from the beginning.

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #3913

### CODE REVIEW

File: delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+                        cachedViews.traverse { v => c.put(v.ref, v) }
+                      }
+      // The destroy action
+      destroyed    <- Ref.of[Task, Option[ActiveViewDef]](None)
+      destroy       = (active: ActiveViewDef) => destroyed.set(Some(active))
+      _            <- CompositeViewsCoordinator.cleanupCurrent(cache, newView, destroy)
+      destroyedOpt <- destroyed.get
+    } yield destroyedOpt
+
+  }
```
Comment (shinyhappydan) [inline delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala:42]: A couple of things
-  Is cache a good name here? My understanding is that this is the set of running views
- If destroy is called multiple times (which could happen if there is a bug) this would not be reflected by this fixture

File: delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+    val existingView = activeView(existingViewRef, 1)
+    val deprecated   = deprecatedView(existingViewRef)
+    cleanup(deprecated, List(existingView)).assertSome(existingView)
+  }
+
+  test("Clean up if the view is updated") {
+    val existingView = activeView(existingViewRef, 1)
+    val updatedView  = activeView(existingViewRef, 2)
+    cleanup(updatedView, List(existingView)).assertSome(existingView)
+  }
```
Comment (shinyhappydan) [inline delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala:71]: These are a bit hard to read

It's going to be clearer if there is more of a given/when/then structure to tests

File: delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala [hunk 3]
```diff
@@ -103,6 +86,34 @@ object CompositeViewsCoordinator {
...
+      destroy: ActiveViewDef => Task[Unit]
+  ): Task[Unit] = {
+    val ref = viewDef.ref
+    cache.get(ref).flatMap { cachedOpt =>
+      (cachedOpt, viewDef) match {
+        case (Some(cached), active: ActiveViewDef) if cached.projection == active.projection =>
+          Task.delay(logger.info(s"Projection '${cached.projection}' is already running and will not be recreated."))
+        case (Some(cached), _: ActiveViewDef)                                                              =>
+          Task.delay(
+            logger.info(s"View '${ref.project}/${ref.viewId}' has been updated, cleaning up the current one.")
```
Comment (shinyhappydan) [inline delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala:101]: We really need a logger which returns tasks because the sclafmt here is painful

File: delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+import ch.epfl.bluebrain.nexus.testkit.bio.BioSuite
+import monix.bio.Task
+
+import java.util.UUID
+
+class CompositeViewsCoordinatorSuite extends BioSuite with CompositeViewsFixture {
+
+  private val existingViewRef                    = ViewRef(projectRef, nxv + "my-view")
+  private val anotherView                        = ViewRef(projectRef, nxv + "another-view")
+  private def activeView(ref: ViewRef, rev: Int) = ActiveViewDef(
```
Comment (shinyhappydan) [inline delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala:19]: `activeViewWithRevision`?

File: delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala (hunk 3 above)
Comment (olivergrabinski) [reply delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala:101]: log4cats

File: delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala (hunk 1 above)
Comment (imsdu) [reply delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala:42]: * It is the same name as in the implementation
* destroy like almost all operations to start/stop indexing is meant to be idempotent

File: delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala [hunk 5]
```diff
@@ -103,6 +86,34 @@ object CompositeViewsCoordinator {
...
+          ) >>
+            destroy(cached)
+        case (Some(cached), _: DeprecatedViewDef)                                                          =>
+          Task.delay(
+            logger.info(s"View '${ref.project}/${ref.viewId}' has been deprecated, cleaning up the current one.")
+          ) >>
+            destroy(cached)
+        case (None, _)                                                                                     =>
```
Comment (olivergrabinski) [inline delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala:109]: Probably out-of-scope but we are missing this now in the ES and BG coordinators

File: delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala [hunk 6]
```diff
@@ -62,39 +62,22 @@ final class CompositeViewsCoordinator(
...
-              _ <- cache.remove(v.ref)
-            } yield ()
-          )
-          .void
-      case None    =>
-        Task.delay(
-          logger.debug(s"View '${ref.project}/${ref.viewId}' is not referenced yet, cleaning is aborted.")
-        )
-    }
+  private def destroy(active: ActiveViewDef) =
```
Comment (olivergrabinski) [inline delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala:70]: If we don't have any abstraction between coordinators, it would be nice to ultimately have the destroy function in ES and BG coordinators as well. The bug was easy to spot when comparing the coordinators as they had the same structure.

**Review by olivergrabinski — APPROVED** [review]

File: delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala (hunk 3 above)
Comment (imsdu) [reply delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala:101]: We have too look into log4cats or some similar library for this.
But in the end, yes

File: delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala (hunk 4 above)
Comment (imsdu) [reply delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala:19]: An active view always include a revision

File: delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala (hunk 5 above)
Comment (imsdu) [reply delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala:109]: Ok, we can have a look at that in another PR

File: delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala (hunk 6 above)
Comment (imsdu) [reply delta/plugins/composite-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinator.scala:70]: We can see if it is worth it even if if an abstraction for 3 cases may be overkill and might be not bring a real gain in the end (the previous implementation in 1.7 had one and it was not a real win).
We must also do this refactor for the construct query before looking for it

File: delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala (hunk 2 above)
Comment (shinyhappydan) [reply delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala:71]: Ok but that doesn't mean these tests are easy to read. Comments should really be a last resort when we can't communicate intent through the code

File: delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala (hunk 1 above)
Comment (imsdu) [reply delta/plugins/composite-views/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/compositeviews/indexing/CompositeViewsCoordinatorSuite.scala]: * I updated the test so that the value can only be set once
* `KeyValueStore` has now one implementation which is a in-memory cache
* This PR aims to fix an issue in production so it is better to keep the change minimal
