### PR TITLE
Do not create an event when updating attributes and digest is not computed

### LINKED ISSUE #4743: When computing the file attributes asynchronously, events are created when they are not yet computed
**Describe the bug**
When a file is linked, its attributes (size + checksum) are computed asynchronously by a task.
This task currently creates events even if attributes are not yet computed

**What part of Nexus is affected**
- [ ] Fusion
- [X] Delta
- [ ] CLI
- [ ] Documentation

**Expected behavior**
An event is registered only when the attributes are computed

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #4743

### CODE REVIEW

File: delta/plugins/storage/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/files/FileAttributesUpdateStream.scala [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+import fs2.Stream
+import retry.RetryPolicies.constantDelay
+import retry.implicits.retrySyntaxError
+
+import scala.concurrent.duration.FiniteDuration
+
+/**
+  * Stream that attempts to update file attributes asynchronously for linked files in remote storages
+  */
+sealed trait FileAttributesUpdateStream
```
Comment (imsdu) [inline delta/plugins/storage/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/files/FileAttributesUpdateStream.scala:25]: Separating from `Files` makes it easier and more consistent with the other long-running tasks (like indexing)

File: delta/plugins/storage/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/storages/StoragesConfig.scala [hunk 2]
```diff
@@ -206,7 +207,7 @@ object StoragesConfig {
       defaultWritePermission: Permission,
       showLocation: Boolean,
       defaultMaxFileSize: Long,
-      digestComputation: RetryStrategyConfig
+      digestComputationRetryDelay: FiniteDuration
```
Comment (imsdu) [inline delta/plugins/storage/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/storages/StoragesConfig.scala:210]: Here, we always want to retry so it is better to just leave the opportunity to define a delay between them.

File: delta/plugins/storage/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/files/Files.scala [hunk 3]
```diff
@@ -700,6 +624,7 @@ object Files {
       case Some(s) if s.rev != c.rev               => IO.raiseError(IncorrectRev(c.rev, s.rev))
       case Some(s) if s.deprecated                 => IO.raiseError(FileIsDeprecated(c.id))
       case Some(s) if s.attributes.digest.computed => IO.raiseError(DigestAlreadyComputed(s.id))
+      case Some(s) if !c.digest.computed           => IO.raiseError(DigestNotComputed(s.id))
```
Comment (olivergrabinski) [inline delta/plugins/storage/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/storage/files/Files.scala:627]: It feels like the issue would have not occurred in the first place if the digest fields in the attribute was an Option maybe?

**Review by olivergrabinski — APPROVED** [review]
